CREATE TABLE `employees` (
                         `id` int(150) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                         `name_of_org_eng` varchar(255) NULL,
                         `name_of_org_ban` varchar(255) NULL,
                         `type_of_org` varchar(150) NULL,
                         `status_of_org` varchar(150) NULL,
                         `ownership_of_org` varchar(150) NULL,
                         `country_of_org` varchar(150) NULL,
                         `name_of_the_project` varchar(255) NULL,
                         `business_sector` varchar(150) NULL,
                         `major_activities` varchar(255) NULL,
                         `first_or_not` tinyint(150) NULL,
                         `contact_name` varchar(150) NULL,
                         `contact_phone` varchar(150) NULL,
                         `pay_amount` int(150) NULL,
                         `total_amount` int(150) NULL,
                         `contact_email` varchar(150) NULL,
                         `contact_address` varchar(150) NULL,
                         `vat_on_pay_amount` int(150) NULL,
                         `all_info_are_correct` varchar(150) NULL
) ENGINE='InnoDB' COLLATE 'utf8mb4_unicode_ci';
